-- Step 1: Fix instagram_videos column
ALTER TABLE cases DROP COLUMN IF EXISTS instagram_videos;
ALTER TABLE cases ADD COLUMN instagram_videos jsonb NOT NULL DEFAULT '[]'::jsonb;

-- Step 1b: Allow skincancer as a gallery value
ALTER TABLE cases DROP CONSTRAINT IF EXISTS cases_gallery_check;
ALTER TABLE cases ADD CONSTRAINT cases_gallery_check CHECK (gallery IN ('comprehensive', 'eyelid', 'midfacelift', 'skincancer'));

-- Step 2: Seed all cases (run this whole file in Supabase SQL Editor)
INSERT INTO cases (gallery, procedures, images, cover_image, display_order, instagram_videos) VALUES

-- MIDFACELIFT
('midfacelift', ARRAY['Invisible Access Mid Facelift'], ARRAY['/ba/midfacelift/case-01-new/01.jpg','/ba/midfacelift/case-01-new/02.jpg','/ba/midfacelift/case-01-new/03.jpg','/ba/midfacelift/case-01-new/04.jpg','/ba/midfacelift/case-01-new/05.jpg','/ba/midfacelift/case-01-new/06.jpg','/ba/midfacelift/case-01-new/07.jpg','/ba/midfacelift/case-01-new/08.jpg','/ba/midfacelift/case-01-new/09.jpg','/ba/midfacelift/case-01-new/10.jpg'], '/ba/midfacelift/case-01-new/01.jpg', 0, '[]'::jsonb),
('midfacelift', ARRAY['Invisible Access Mid Facelift'], ARRAY['/ba/midfacelift/case-02/01.jpeg','/ba/midfacelift/case-02/02.jpeg','/ba/midfacelift/case-02/03.jpeg','/ba/midfacelift/case-02/04.jpeg','/ba/midfacelift/case-02/05.jpeg'], '/ba/midfacelift/case-02/01.jpeg', 10, '[]'::jsonb),

-- COMPREHENSIVE
('comprehensive', ARRAY['Deep Plane Face and Neck Lift with Submandibular Gland Sculpting','Buccal Fat Contouring','Fat Transfer','Laser Resurfacing'], ARRAY['/ba/hc/01.jpg','/ba/hc/02.jpg','/ba/hc/03.jpg','/ba/hc/04.jpg','/ba/hc/05.jpg','/ba/hc/1month/01.jpg','/ba/hc/1month/02.jpg','/ba/hc/1month/03.jpg','/ba/hc/1month/04.jpg','/ba/hc/1month/05.jpg'], '/ba/hc/01.jpg', 0, '[]'::jsonb),
('comprehensive', ARRAY['Deep Plane Face and Neck Lift','Upper Blepharoplasty','Lower Blepharoplasty','Brow Lift','Fat Transfer','Laser Resurfacing'], ARRAY['/ba/comprehensive/case-04/01.jpeg','/ba/comprehensive/case-04/02.jpeg','/ba/comprehensive/case-04/03.jpeg','/ba/comprehensive/case-04/04.jpeg','/ba/comprehensive/case-04/05.jpeg','/ba/comprehensive/case-04/06.jpeg','/ba/comprehensive/case-04/07.jpeg'], '/ba/comprehensive/case-04/01.jpeg', 10, '[{"url":"https://www.instagram.com/reel/DP2C4LOkotZ/?igsh=MWlmMDg1MjltZ2VrYw%3D%3D","label":"Watch Patient''s 1 Week Post Op"}]'::jsonb),
('comprehensive', ARRAY['Deep Plane Face and Neck Lift','Upper Blepharoplasty','Lower Blepharoplasty','Brow Lift','Lip Lift','Fat Transfer','Laser Resurfacing','Ptosis Repair'], ARRAY['/ba/comprehensive/case-05/01.jpeg','/ba/comprehensive/case-05/02.jpeg','/ba/comprehensive/case-05/03.jpeg','/ba/comprehensive/case-05/04.jpeg','/ba/comprehensive/case-05/05.jpeg','/ba/comprehensive/case-05/06.jpeg','/ba/comprehensive/case-05/07.jpeg','/ba/comprehensive/case-05/08.jpeg','/ba/comprehensive/case-05/09.jpeg','/ba/comprehensive/case-05/10.jpeg','/ba/comprehensive/case-05/11.jpeg','/ba/comprehensive/case-05/12.jpeg'], '/ba/comprehensive/case-05/01.jpeg', 20, '[{"url":"https://www.instagram.com/reel/DV1Uyy7D8ta/?igsh=dnIyZjZsYzB6cDlx","label":"Watch Dr. Nia Walk Through This Case"},{"url":"https://www.instagram.com/reel/DMGAk4RxuMm/?igsh=MWNxZHdzcTJxYjQ0OA==","label":"Watch Patient''s 5 Months Post Op"}]'::jsonb),
('comprehensive', ARRAY['Brow Lift','Upper Blepharoplasty','Ptosis Repair','Lower Blepharoplasty','Deep Plane Face and Neck Lift with Submandibular Gland Sculpting','Buccal Fat Contouring','Fat Transfer','Laser Resurfacing'], ARRAY['/ba/comprehensive/case-09/01.jpeg','/ba/comprehensive/case-09/02.jpeg','/ba/comprehensive/case-09/03.jpeg','/ba/comprehensive/case-09/04.jpeg','/ba/comprehensive/case-09/05.jpeg','/ba/comprehensive/case-09/06.jpeg','/ba/comprehensive/case-09/07.jpeg','/ba/comprehensive/case-09/08.jpeg'], '/ba/comprehensive/case-09/05.jpeg', 30, '[{"url":"https://www.instagram.com/reel/DU_oNAOkkGP/?igsh=MWE2bmYxOG5mNHhpaA%3D%3D","label":"Watch Patient''s 1 Week Post Op"}]'::jsonb),
('comprehensive', ARRAY['Deep Plane Face and Neck Lift','Upper Blepharoplasty','Lower Blepharoplasty','Brow Lift','Fat Transfer','Lip Lift','Laser Resurfacing'], ARRAY['/ba/comprehensive/case-01/01.jpeg','/ba/comprehensive/case-01/02.jpeg','/ba/comprehensive/case-01/03.jpeg','/ba/comprehensive/case-01/04.jpeg','/ba/comprehensive/case-01/05.jpeg','/ba/comprehensive/case-01/06.jpeg','/ba/comprehensive/case-01/07.jpeg','/ba/comprehensive/case-01/08.jpeg'], '/ba/comprehensive/case-01/01.jpeg', 40, '[]'::jsonb),
('comprehensive', ARRAY['Deep Plane Face and Neck Lift','Upper Blepharoplasty','Lower Blepharoplasty','Fat Transfer'], ARRAY['/ba/comprehensive/case-03/01.jpeg','/ba/comprehensive/case-03/02.jpeg','/ba/comprehensive/case-03/03.jpeg','/ba/comprehensive/case-03/04.jpeg'], '/ba/comprehensive/case-03/01.jpeg', 50, '[]'::jsonb),
('comprehensive', ARRAY['Deep Plane Face and Neck Lift','Fat Transfer'], ARRAY['/ba/comprehensive/case-06/01.jpeg','/ba/comprehensive/case-06/02.jpeg'], '/ba/comprehensive/case-06/01.jpeg', 60, '[]'::jsonb),
('comprehensive', ARRAY['Deep Plane Face and Neck Lift','Upper Blepharoplasty','Lower Blepharoplasty','Fat Transfer','Laser Resurfacing'], ARRAY['/ba/comprehensive/case-07/01.jpeg','/ba/comprehensive/case-07/02.jpeg','/ba/comprehensive/case-07/03.jpeg','/ba/comprehensive/case-07/04.jpeg','/ba/comprehensive/case-07/05.jpeg','/ba/comprehensive/case-07/06.jpeg','/ba/comprehensive/case-07/07.jpeg'], '/ba/comprehensive/case-07/01.jpeg', 70, '[]'::jsonb),
('comprehensive', ARRAY['Deep Plane Face and Neck Lift','Upper Blepharoplasty','Lower Blepharoplasty','Fat Transfer','Laser Resurfacing'], ARRAY['/ba/comprehensive/case-08/01.jpeg','/ba/comprehensive/case-08/02.jpeg','/ba/comprehensive/case-08/03.jpeg','/ba/comprehensive/case-08/04.jpeg','/ba/comprehensive/case-08/05.jpeg','/ba/comprehensive/case-08/06.jpeg'], '/ba/comprehensive/case-08/01.jpeg', 80, '[]'::jsonb),
('comprehensive', ARRAY['Deep Plane Face and Neck Lift','Upper Blepharoplasty','Lower Blepharoplasty','Fat Transfer','Laser Resurfacing'], ARRAY['/ba/comprehensive/case-02/01.jpeg','/ba/comprehensive/case-02/02.jpeg','/ba/comprehensive/case-02/03.jpeg','/ba/comprehensive/case-02/04.jpeg','/ba/comprehensive/case-02/05.jpeg','/ba/comprehensive/case-02/06.jpeg','/ba/comprehensive/case-02/07.jpeg','/ba/comprehensive/case-02/08.jpeg','/ba/comprehensive/case-02/09.jpeg','/ba/comprehensive/case-02/10.jpeg'], '/ba/comprehensive/case-02/01.jpeg', 90, '[]'::jsonb),

-- EYELID
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-01/01.jpeg','/ba/eyelid/case-01/02.jpeg','/ba/eyelid/case-01/03.jpeg','/ba/eyelid/case-01/04.jpeg'], '/ba/eyelid/case-01/01.jpeg', 0, '[]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-03/01.jpeg','/ba/eyelid/case-03/02.jpeg','/ba/eyelid/case-03/03.jpeg','/ba/eyelid/case-03/04.jpeg','/ba/eyelid/case-03/05.jpeg'], '/ba/eyelid/case-03/01.jpeg', 10, '[]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-02/01.jpeg','/ba/eyelid/case-02/02.jpeg','/ba/eyelid/case-02/03.jpeg'], '/ba/eyelid/case-02/01.jpeg', 20, '[]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-04/01.jpeg','/ba/eyelid/case-04/02.jpeg','/ba/eyelid/case-04/03.jpeg'], '/ba/eyelid/case-04/01.jpeg', 30, '[]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-05/01.jpeg','/ba/eyelid/case-05/02.jpeg','/ba/eyelid/case-05/03.jpeg','/ba/eyelid/case-05/04.jpeg','/ba/eyelid/case-05/05.jpeg','/ba/eyelid/case-05/06.jpeg','/ba/eyelid/case-05/07.jpeg','/ba/eyelid/case-05/08.jpeg','/ba/eyelid/case-05/09.jpeg','/ba/eyelid/case-05/10.jpeg','/ba/eyelid/case-05/11.jpeg','/ba/eyelid/case-05/12.jpeg','/ba/eyelid/case-05/13.jpeg','/ba/eyelid/case-05/14.jpeg','/ba/eyelid/case-05/15.jpeg','/ba/eyelid/case-05/16.jpeg','/ba/eyelid/case-05/17.jpeg','/ba/eyelid/case-05/18.jpeg','/ba/eyelid/case-05/19.jpeg'], '/ba/eyelid/case-05/01.jpeg', 40, '[]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-06/01.jpeg','/ba/eyelid/case-06/02.jpeg','/ba/eyelid/case-06/03.jpeg'], '/ba/eyelid/case-06/01.jpeg', 50, '[{"url":"https://www.instagram.com/reel/DNqd231x_64/?igsh=MTYybmN6bWNraDVpaA%3D%3D","label":"Watch Patient''s Transformation"}]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-07/01.jpeg','/ba/eyelid/case-07/02.jpeg','/ba/eyelid/case-07/03.jpeg','/ba/eyelid/case-07/04.jpeg'], '/ba/eyelid/case-07/01.jpeg', 60, '[]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-08/01.jpeg','/ba/eyelid/case-08/02.jpeg','/ba/eyelid/case-08/03.jpeg','/ba/eyelid/case-08/04.jpeg','/ba/eyelid/case-08/05.jpeg'], '/ba/eyelid/case-08/01.jpeg', 70, '[]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-09/01.jpeg','/ba/eyelid/case-09/02.jpeg','/ba/eyelid/case-09/03.jpeg'], '/ba/eyelid/case-09/01.jpeg', 80, '[]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-10/01.jpeg','/ba/eyelid/case-10/02.jpeg','/ba/eyelid/case-10/03.jpeg'], '/ba/eyelid/case-10/01.jpeg', 90, '[]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-11/01.jpeg','/ba/eyelid/case-11/02.jpeg','/ba/eyelid/case-11/03.jpeg','/ba/eyelid/case-11/04.jpeg','/ba/eyelid/case-11/05.jpeg','/ba/eyelid/case-11/06.jpeg'], '/ba/eyelid/case-11/01.jpeg', 100, '[]'::jsonb),
('eyelid', ARRAY['Brow Lift'], ARRAY['/ba/eyelid/case-12/01.jpeg','/ba/eyelid/case-12/02.jpeg','/ba/eyelid/case-12/03.jpeg','/ba/eyelid/case-12/04.jpeg','/ba/eyelid/case-12/05.jpeg','/ba/eyelid/case-12/06.jpeg','/ba/eyelid/case-12/07.jpeg','/ba/eyelid/case-12/08.jpeg'], '/ba/eyelid/case-12/01.jpeg', 110, '[]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-13/01.jpeg','/ba/eyelid/case-13/02.jpeg','/ba/eyelid/case-13/03.jpeg','/ba/eyelid/case-13/04.jpeg','/ba/eyelid/case-13/05.jpeg'], '/ba/eyelid/case-13/01.jpeg', 120, '[]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-14/01.jpeg','/ba/eyelid/case-14/02.jpeg','/ba/eyelid/case-14/03.jpeg','/ba/eyelid/case-14/04.jpeg','/ba/eyelid/case-14/05.jpeg','/ba/eyelid/case-14/06.jpeg','/ba/eyelid/case-14/07.jpeg'], '/ba/eyelid/case-14/01.jpeg', 130, '[]'::jsonb),
('eyelid', ARRAY['Upper and Lower Blepharoplasty'], ARRAY['/ba/eyelid/case-15/01.jpeg','/ba/eyelid/case-15/02.jpeg','/ba/eyelid/case-15/03.jpeg'], '/ba/eyelid/case-15/01.jpeg', 140, '[]'::jsonb),

-- SKIN CANCER
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/01.jpeg'],'/ba/skincancer/01.jpeg',0,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/02.jpeg'],'/ba/skincancer/02.jpeg',10,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/03.jpeg'],'/ba/skincancer/03.jpeg',20,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/04.jpeg'],'/ba/skincancer/04.jpeg',30,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/05.jpeg'],'/ba/skincancer/05.jpeg',40,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/06.jpeg'],'/ba/skincancer/06.jpeg',50,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/07.jpeg'],'/ba/skincancer/07.jpeg',60,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/08.jpeg'],'/ba/skincancer/08.jpeg',70,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/09.jpeg'],'/ba/skincancer/09.jpeg',80,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/10.jpeg'],'/ba/skincancer/10.jpeg',90,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/11.jpeg'],'/ba/skincancer/11.jpeg',100,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/12.jpeg'],'/ba/skincancer/12.jpeg',110,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/13.jpeg'],'/ba/skincancer/13.jpeg',120,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/14.jpeg'],'/ba/skincancer/14.jpeg',130,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/15.jpeg'],'/ba/skincancer/15.jpeg',140,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/16.jpeg'],'/ba/skincancer/16.jpeg',150,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/17.jpeg'],'/ba/skincancer/17.jpeg',160,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/18.jpeg'],'/ba/skincancer/18.jpeg',170,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/19.jpeg'],'/ba/skincancer/19.jpeg',180,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/20.jpeg'],'/ba/skincancer/20.jpeg',190,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/21.jpeg'],'/ba/skincancer/21.jpeg',200,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/22.jpeg'],'/ba/skincancer/22.jpeg',210,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/23.jpeg'],'/ba/skincancer/23.jpeg',220,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/24.jpeg'],'/ba/skincancer/24.jpeg',230,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/25.jpeg'],'/ba/skincancer/25.jpeg',240,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/26.jpeg'],'/ba/skincancer/26.jpeg',250,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/27.jpeg'],'/ba/skincancer/27.jpeg',260,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/28.jpeg'],'/ba/skincancer/28.jpeg',270,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/29.jpeg'],'/ba/skincancer/29.jpeg',280,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/30.jpeg'],'/ba/skincancer/30.jpeg',290,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/31.jpeg'],'/ba/skincancer/31.jpeg',300,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/32.jpeg'],'/ba/skincancer/32.jpeg',310,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/33.jpeg'],'/ba/skincancer/33.jpeg',320,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/34.jpeg'],'/ba/skincancer/34.jpeg',330,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/35.jpeg'],'/ba/skincancer/35.jpeg',340,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/36.jpeg'],'/ba/skincancer/36.jpeg',350,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/37.jpeg'],'/ba/skincancer/37.jpeg',360,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/38.jpeg'],'/ba/skincancer/38.jpeg',370,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/39.jpeg'],'/ba/skincancer/39.jpeg',380,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/40.jpeg'],'/ba/skincancer/40.jpeg',390,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/41.jpeg'],'/ba/skincancer/41.jpeg',400,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/42.jpeg'],'/ba/skincancer/42.jpeg',410,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/43.jpeg'],'/ba/skincancer/43.jpeg',420,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/44.jpeg'],'/ba/skincancer/44.jpeg',430,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/45.jpeg'],'/ba/skincancer/45.jpeg',440,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/46.jpeg'],'/ba/skincancer/46.jpeg',450,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/47.jpeg'],'/ba/skincancer/47.jpeg',460,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/48.jpeg'],'/ba/skincancer/48.jpeg',470,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/49.jpeg'],'/ba/skincancer/49.jpeg',480,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/50.jpeg'],'/ba/skincancer/50.jpeg',490,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/51.jpeg'],'/ba/skincancer/51.jpeg',500,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/52.jpeg'],'/ba/skincancer/52.jpeg',510,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/53.jpeg'],'/ba/skincancer/53.jpeg',520,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/54.jpeg'],'/ba/skincancer/54.jpeg',530,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/55.jpeg'],'/ba/skincancer/55.jpeg',540,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/56.jpeg'],'/ba/skincancer/56.jpeg',550,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/57.jpeg'],'/ba/skincancer/57.jpeg',560,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/58.jpeg'],'/ba/skincancer/58.jpeg',570,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/59.jpeg'],'/ba/skincancer/59.jpeg',580,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/60.jpeg'],'/ba/skincancer/60.jpeg',590,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/61.jpeg'],'/ba/skincancer/61.jpeg',600,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/62.jpeg'],'/ba/skincancer/62.jpeg',610,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/63.jpeg'],'/ba/skincancer/63.jpeg',620,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/64.jpeg'],'/ba/skincancer/64.jpeg',630,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/65.jpeg'],'/ba/skincancer/65.jpeg',640,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/66.jpeg'],'/ba/skincancer/66.jpeg',650,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/67.jpeg'],'/ba/skincancer/67.jpeg',660,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/68.jpeg'],'/ba/skincancer/68.jpeg',670,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/69.jpeg'],'/ba/skincancer/69.jpeg',680,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/70.jpeg'],'/ba/skincancer/70.jpeg',690,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/71.jpeg'],'/ba/skincancer/71.jpeg',700,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/72.jpeg'],'/ba/skincancer/72.jpeg',710,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/73.jpeg'],'/ba/skincancer/73.jpeg',720,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/74.jpeg'],'/ba/skincancer/74.jpeg',730,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/75.jpeg'],'/ba/skincancer/75.jpeg',740,'[]'::jsonb),
('skincancer',ARRAY['Skin Cancer Reconstruction'],ARRAY['/ba/skincancer/76.jpeg'],'/ba/skincancer/76.jpeg',750,'[]'::jsonb);
